name: custom-model-hol
channels:
  - https://repo.anaconda.com/pkgs/snowflake
dependencies:
  - python=3.10
  - joblib==1.2.0
  - snowflake-snowpark-python
  - snowflake-ml-python
  - scipy==1.11.4 # This is due to a PyCaret Issue with later versions
  - pycaret
  - notebook
  - scikit-learn